FROM apache/airflow:2.8.0-python3.11

USER root

RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    yfinance \
    confluent-kafka \
    pandas \
    pyarrow \
    boto3 \
    python-dotenv \
    redshift-connector \
    sqlalchemy \
    pytz \
    dbt-redshift